# Generated by Django 5.2 on 2025-04-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Producto')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre de Producto')),
                ('descripcion', models.TextField(verbose_name='Descripcion del Producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=50, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('contrasena', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
            ],
        ),
    ]
