# Generated by Django 5.2 on 2025-04-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeelab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del archivo de imagen (en static/img/)'),
        ),
    ]
