# Generated by Django 5.2 on 2025-05-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeelab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('cliente', 'Cliente')], default='cliente', max_length=20, verbose_name='Rol'),
        ),
    ]
